"""Versioned CSV schema for titration data collection."""

from __future__ import annotations

from .ml_features import DERIVED_ML_COLUMNS

SCHEMA_VERSION = "1.8"

EXPERIMENT_COLUMNS = [
    "schema_version",
    "experiment_id",
    "titration_type",
    "sample_name",
    "sample_concentration_M",
    "sample_volume_ml",
    "sample_valence",
    "titrant_name",
    "titrant_concentration_M",
    "titrant_valence",
    "Ka",
    "Kb",
    "indicator",
    "chemistry_model",
    "chemistry_model_version",
    "constants_source",
    "constants_source_id",
    "constants_query",
    "constants_candidate_count",
    "constants_lookup_ambiguous",
    "constants_confirmation_status",
    "constants_warning",
    "selected_pka_type",
    "selected_pka_value",
    "selected_pka_temperature_c",
    "activity_model",
    "ionic_strength_m",
    "ionic_strength_label",
    "activity_warning",
    "theoretical_equivalence_pH",
    "selected_equivalence_step",
    "indicator_transition_low_pH",
    "indicator_transition_high_pH",
    "indicator_endpoint_volume_ml",
    "indicator_endpoint_offset_ml",
    "indicator_endpoint_confidence",
    "indicator_endpoint_warning",
    "standard_solution_uncertainty_note",
    "equivalence_formula",
    "calculated_theoretical_equivalence_volume_ml",
    "sample_concentration_from_theoretical_equivalence_M",
    "theoretical_equivalence_volume_ml",
    "reference_equivalence_volume_ml",
    "observed_color_endpoint_volume_ml",
    "predicted_equivalence_volume_ml",
    "sample_concentration_from_predicted_equivalence_M",
    "predicted_sample_concentration_error_percent",
    "predicted_equivalence_pH",
    "predicted_equivalence_pH_model",
    "predicted_equivalence_pH_warning",
    "predicted_equivalence_confidence",
    "predicted_equivalence_source",
    "predicted_equivalence_evidence",
]

PUMP_COLUMNS = [
    "pump_mode",
    "pump_state",
    "pump_step_count",
    "pump_commanded_step_count",
    "pump_confirmed_step_count",
    "pump_elapsed_s",
    "pump_run_rate_ml_per_s",
    "pump_calibrated_ml_per_step",
    "pump_calibrated_steps_per_ml",
    "commanded_volume_ml",
    "confirmed_injected_volume_ml",
]

FRAME_COLUMNS = [
    "csv_session_id",
    "csv_row_index",
    "csv_recording_started_epoch_s",
    "csv_recording_elapsed_s",
    "csv_mark_sequence",
    "csv_event_note",
    "time_s",
    "frame_id",
    "thermal_time_s",
    "visible_time_s",
    "sync_offset_ms",
    "sync_method",
    "sync_quality",
    "sync_warning",
    "injected_volume_ml",
    "theoretical_equivalence_time_s",
    "distance_to_equivalence_ml",
    "time_to_equivalence_s",
    "equivalence_window_ml",
    "equivalence_window_label",
    "sample_concentration_from_injected_M",
    "sample_concentration_error_percent",
]

VISIBLE_COLUMNS = [
    "visible_R_mean",
    "visible_G_mean",
    "visible_B_mean",
    "visible_H_mean",
    "visible_S_mean",
    "visible_V_mean",
    "visible_H_delta",
    "visible_S_delta",
    "visible_V_delta",
    "visible_HSV_delta",
    "visible_color_delta",
]

THERMAL_COLUMNS = [
    "thermal_R_mean",
    "thermal_G_mean",
    "thermal_B_mean",
    "thermal_H_mean",
    "thermal_S_mean",
    "thermal_V_mean",
    "thermal_H_delta",
    "thermal_S_delta",
    "thermal_V_delta",
    "thermal_HSV_delta",
    "thermal_color_delta",
    "thermal_source",
    "thermal_roi_avg",
    "thermal_roi_max",
    "thermal_roi_min",
    "thermal_roi_std",
    "thermal_roi_range",
    "thermal_roi_iqr",
    "thermal_roi_p05",
    "thermal_roi_p25",
    "thermal_roi_p50",
    "thermal_roi_p75",
    "thermal_roi_p95",
    "thermal_roi_hot_fraction",
    "thermal_roi_cold_fraction",
    "thermal_roi_min_x",
    "thermal_roi_min_y",
    "thermal_roi_max_x",
    "thermal_roi_max_y",
    "thermal_roi_delta",
    "thermal_matrix_avg",
    "thermal_matrix_max",
    "thermal_matrix_min",
    "thermal_matrix_std",
    "thermal_matrix_range",
    "thermal_matrix_iqr",
    "thermal_matrix_p05",
    "thermal_matrix_p25",
    "thermal_matrix_p50",
    "thermal_matrix_p75",
    "thermal_matrix_p95",
    "thermal_matrix_min_x",
    "thermal_matrix_min_y",
    "thermal_matrix_max_x",
    "thermal_matrix_max_y",
    "thermal_matrix_shape",
    "thermal_raw_roi_avg",
    "thermal_raw_roi_max",
    "thermal_raw_roi_min",
    "thermal_raw_roi_std",
    "thermal_raw_roi_range",
    "thermal_raw_roi_iqr",
    "thermal_raw_roi_p05",
    "thermal_raw_roi_p25",
    "thermal_raw_roi_p50",
    "thermal_raw_roi_p75",
    "thermal_raw_roi_p95",
    "thermal_raw_roi_hot_fraction",
    "thermal_raw_roi_cold_fraction",
    "thermal_raw_roi_delta",
    "thermal_raw_roi_min_x",
    "thermal_raw_roi_min_y",
    "thermal_raw_roi_max_x",
    "thermal_raw_roi_max_y",
    "thermal_raw_min",
    "thermal_raw_max",
    "thermal_raw_mean",
    "thermal_raw_std",
    "thermal_raw_range",
    "thermal_raw_iqr",
    "thermal_raw_p05",
    "thermal_raw_p25",
    "thermal_raw_p50",
    "thermal_raw_p75",
    "thermal_raw_p95",
    "thermal_frame_rate_hz",
    "thermal_conversion_model",
    "thermal_conversion_calibration_source",
    "thermal_calibrated",
]

ML_DERIVED_COLUMNS = list(DERIVED_ML_COLUMNS)

STATUS_COLUMNS = [
    "status_label",
    "status_confidence",
    "source_quality",
    "warnings",
]

EQUIVALENCE_RESULT_COLUMNS = [
    "estimated_equivalence_time_s",
    "estimated_equivalence_volume_ml",
    "equivalence_confidence",
    "absolute_volume_error_ml",
    "relative_volume_error_percent",
]

DEFAULT_COLUMNS = (
    EXPERIMENT_COLUMNS
    + PUMP_COLUMNS
    + FRAME_COLUMNS
    + VISIBLE_COLUMNS
    + THERMAL_COLUMNS
    + ML_DERIVED_COLUMNS
    + STATUS_COLUMNS
    + EQUIVALENCE_RESULT_COLUMNS
)

UNITS_BY_COLUMN = {
    "sample_concentration_M": "mol/L",
    "sample_volume_ml": "mL",
    "titrant_concentration_M": "mol/L",
    "theoretical_equivalence_volume_ml": "mL",
    "reference_equivalence_volume_ml": "mL",
    "observed_color_endpoint_volume_ml": "mL",
    "predicted_equivalence_volume_ml": "mL",
    "sample_concentration_from_predicted_equivalence_M": "mol/L",
    "predicted_sample_concentration_error_percent": "%",
    "predicted_equivalence_pH": "pH",
    "predicted_equivalence_confidence": "0-1",
    "selected_pka_value": "pKa",
    "selected_pka_temperature_c": "degC",
    "ionic_strength_m": "mol/L",
    "theoretical_equivalence_pH": "pH",
    "indicator_transition_low_pH": "pH",
    "indicator_transition_high_pH": "pH",
    "indicator_endpoint_volume_ml": "mL",
    "indicator_endpoint_offset_ml": "mL",
    "calculated_theoretical_equivalence_volume_ml": "mL",
    "sample_concentration_from_theoretical_equivalence_M": "mol/L",
    "pump_calibrated_ml_per_step": "mL/step",
    "pump_calibrated_steps_per_ml": "step/mL",
    "commanded_volume_ml": "mL",
    "confirmed_injected_volume_ml": "mL",
    "pump_elapsed_s": "s",
    "pump_run_rate_ml_per_s": "mL/s",
    "csv_recording_started_epoch_s": "Unix epoch s",
    "csv_recording_elapsed_s": "s",
    "time_s": "s",
    "thermal_time_s": "s",
    "visible_time_s": "s",
    "sync_offset_ms": "ms",
    "injected_volume_ml": "mL",
    "theoretical_equivalence_time_s": "s",
    "distance_to_equivalence_ml": "mL",
    "time_to_equivalence_s": "s",
    "equivalence_window_ml": "mL",
    "sample_concentration_from_injected_M": "mol/L",
    "sample_concentration_error_percent": "%",
    "visible_H_mean": "degree",
    "visible_H_delta": "degree",
    "visible_S_delta": "ratio/frame",
    "visible_V_delta": "ratio/frame",
    "visible_HSV_delta": "normalized HSV distance/frame",
    "thermal_H_mean": "degree",
    "thermal_H_delta": "degree",
    "thermal_S_delta": "ratio/frame",
    "thermal_V_delta": "ratio/frame",
    "thermal_HSV_delta": "normalized HSV distance/frame",
    "thermal_roi_avg": "degC",
    "thermal_roi_max": "degC",
    "thermal_roi_min": "degC",
    "thermal_roi_std": "degC",
    "thermal_roi_range": "degC",
    "thermal_roi_iqr": "degC",
    "thermal_roi_p05": "degC",
    "thermal_roi_p25": "degC",
    "thermal_roi_p50": "degC",
    "thermal_roi_p75": "degC",
    "thermal_roi_p95": "degC",
    "thermal_roi_delta": "degC/frame",
    "thermal_matrix_avg": "degC",
    "thermal_matrix_max": "degC",
    "thermal_matrix_min": "degC",
    "thermal_matrix_std": "degC",
    "thermal_matrix_range": "degC",
    "thermal_matrix_iqr": "degC",
    "thermal_matrix_p05": "degC",
    "thermal_matrix_p25": "degC",
    "thermal_matrix_p50": "degC",
    "thermal_matrix_p75": "degC",
    "thermal_matrix_p95": "degC",
    "thermal_raw_roi_avg": "raw uint16",
    "thermal_raw_roi_max": "raw uint16",
    "thermal_raw_roi_min": "raw uint16",
    "thermal_raw_roi_std": "raw uint16",
    "thermal_raw_roi_range": "raw uint16",
    "thermal_raw_roi_iqr": "raw uint16",
    "thermal_raw_roi_p05": "raw uint16",
    "thermal_raw_roi_p25": "raw uint16",
    "thermal_raw_roi_p50": "raw uint16",
    "thermal_raw_roi_p75": "raw uint16",
    "thermal_raw_roi_p95": "raw uint16",
    "thermal_raw_roi_delta": "raw uint16/frame",
    "thermal_raw_min": "raw uint16",
    "thermal_raw_max": "raw uint16",
    "thermal_raw_mean": "raw uint16",
    "thermal_raw_range": "raw uint16",
    "thermal_raw_iqr": "raw uint16",
    "thermal_raw_p05": "raw uint16",
    "thermal_raw_p25": "raw uint16",
    "thermal_raw_p50": "raw uint16",
    "thermal_raw_p75": "raw uint16",
    "thermal_raw_p95": "raw uint16",
    "thermal_raw_std": "raw uint16",
    "thermal_frame_rate_hz": "Hz",
    "visible_H_baseline_delta": "degree",
    "visible_S_baseline_delta": "ratio",
    "visible_V_baseline_delta": "ratio",
    "visible_HSV_baseline_delta": "normalized HSV distance",
    "visible_color_baseline_delta": "RGB distance",
    "visible_H_slope_deg_per_s": "degree/s",
    "visible_S_slope_per_s": "ratio/s",
    "visible_V_slope_per_s": "ratio/s",
    "visible_HSV_delta_mean_1s": "normalized HSV distance/frame",
    "visible_HSV_delta_max_1s": "normalized HSV distance/frame",
    "visible_color_delta_mean_1s": "RGB distance/frame",
    "visible_color_delta_max_1s": "RGB distance/frame",
    "thermal_roi_avg_baseline_delta": "degC",
    "thermal_roi_p95_baseline_delta": "degC",
    "thermal_roi_avg_slope_c_per_s": "degC/s",
    "thermal_roi_p95_slope_c_per_s": "degC/s",
    "thermal_roi_delta_mean_1s": "degC/frame",
    "thermal_roi_delta_max_1s": "degC/frame",
    "thermal_raw_roi_p50_baseline_delta": "raw uint16",
    "thermal_raw_roi_p95_baseline_delta": "raw uint16",
    "thermal_raw_roi_p50_slope_per_s": "raw uint16/s",
    "thermal_raw_roi_p95_slope_per_s": "raw uint16/s",
    "thermal_raw_roi_delta_mean_1s": "raw uint16/frame",
    "thermal_raw_roi_delta_max_1s": "raw uint16/frame",
    "abs_sync_offset_ms": "ms",
    "training_quality_score": "0..1",
    "valid_for_training": "0/1",
    "estimated_equivalence_time_s": "s",
    "estimated_equivalence_volume_ml": "mL",
    "absolute_volume_error_ml": "mL",
    "relative_volume_error_percent": "%",
}
