const fs = require('fs');
const view = require('../../website/demo-view.js');
const nodeAssert = require('assert');
nodeAssert.strictEqual(view.observedStage({state:'recording',pump_state:'retract',pump_dosing_stage:'fast',auto_stop_pulse_state:'slow_continuous'}).label,'되감기');
nodeAssert.strictEqual(view.observedStage({state:'recording',pump_state:'stop',pump_dosing_stage:'fast'}).label,'주입 정지');
let harness=fs.readFileSync('tests/js/test_web_request_lifecycle.js','utf8').split('(async () => {\n  await testPumpLifecycle();')[0];
eval(harness + `
(async()=>{
 requests.length=0;
 vm.runInContext("liveStreamBase='http://server-a';",context);
 const pending=context.refreshCsvStatus();
 vm.runInContext("liveStreamBase='http://server-b';resetDemoViewForBackend();",context);
 context.applyCsvStatus({state:'idle',session_id:2,started_epoch_s:100,updated_epoch_s:110},{source:'get'});
 requests[0].resolve({ok:true,csv:{state:'recording',session_id:1,started_epoch_s:999,updated_epoch_s:1000}});
 await pending;
 assert(vm.runInContext('latestCsvStatus.session_id',context)===2,'old server GET replaced new state');
 requests.length=0;
 const motion=context.sendPumpCommand('/api/pump/dispense','sending A');
 const old=requests[0];
 vm.runInContext("liveStreamBase='http://server-a';resetDemoViewForBackend();",context);
 const stop=context.sendPumpCommand('/api/pump/stop','stopping new');
 assert(requests.length===2,'new server STOP blocked by old command');
 requests[1].resolve({ok:true,pump:{action:'stop',command:'c',sent:true,status:'sent'}});
 await stop;
 const label=element('pumpCommandStatus').textContent;
 old.resolve({ok:true,pump:{action:'start',sent:true,status:'sent'}});
 await motion;
 assert(element('pumpCommandStatus').textContent===label,'old motion response replaced stop');
 requests.length=0;
 const health=context.refreshCollectorHealth();
 vm.runInContext("liveStreamBase='http://server-b';resetDemoViewForBackend();liveStreamBase='http://server-a';resetDemoViewForBackend();",context);
 element('healthActionValue').textContent='new connection';
 requests[0].resolve({ok:false,error:'old error'},{ok:false,status:502});
 await health;
 assert(element('healthActionValue').textContent==='new connection','A-B-A old error not fenced');
 assert(requests.every(r=>!r.url.includes('/api/csv/start')),'fence auto-started recording');
 console.log('retract/stop mapping and stale backend response fences OK');
})().catch(e=>{console.error(e);process.exitCode=1;});
`);
